// HOME SCREEN ACTIONS
export const FETCH_LATEST_MOVIES = "FETCH_LATEST_MOVIES";
export const SET_LATEST_MOVIES = "SET_LATEST_MOVIES";
export const FETCH_LATEST_MOVIES_FAILED = "FETCH_LATEST_MOVIES_FAILED";

export const FETCH_POPULAR_MOVIES = "FETCH_POPULAR_MOVIES";
export const SET_POPULAR_MOVIES = "SET_POPULAR_MOVIES";
export const FETCH_POPULAR_MOVIES_FAILED = "FETCH_POPULAR_MOVIES_FAILED";

export const FETCH_TOP_RATED_MOVIES = "FETCH_TOP_RATED_MOVIES";
export const SET_TOP_RATED_MOVIES = "SET_TOP_RATED_MOVIES";
export const FETCH_TOP_RATED_MOVIES_FAILED = "FETCH_TOP_RATED_MOVIES_FAILED";

export const FETCH_UPCOMING_MOVIES = "FETCH_UPCOMING_MOVIES";
export const SET_UPCOMING_MOVIES = "SET_UPCOMING_MOVIES";
export const FETCH_UPCOMING_MOVIES_FAILED = "FETCH_UPCOMING_MOVIES_FAILED";

// DETAILS ACTIONS
export const GET_MOVIE_DETAILS = "GET_MOVIE_DETAILS";
export const SET_MOVIE_DETAILS = "SET_MOVIE_DETAILS";
export const SET_MOVIE_CREDITS = "SET_MOVIE_CREDITS";
export const GET_MOVIE_DETAILS_FAILED = "GET_MOVIE_DETAILS_FAILED";

export const GET_PERSON_DETAILS = "GET_PERSON_DETAILS";
export const SET_PERSON_DETAILS = "SET_PERSON_DETAILS";
export const SET_PERSON_EXTERNAL_IDS = "SET_PERSON_EXTERNAL_IDS";
export const GET_PERSON_DETAILS_FAILED = "GET_PERSON_DETAILS_FAILED";

// SEARCH ACTIONS
export const SEARCH_MOVIES = "SEARCH_MOVIES";
export const SEARCH_PEOPLE = "SEARCH_PEOPLE";
export const SEARCH_MOVIES_SUCCEED = "SEARCH_MOVIES_SUCCEED";
export const SEARCH_PEOPLE_SUCCEED = "SEARCH_PEOPLE_SUCCEED";
export const SEARCH_FAILED = "SEARCH_FAILED";

// CATEGORIES ACTION
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const FETCH_CATEGORIES_FAILED = "FETCH_CATEGORIES_FAILED";

export const GET_DISCOVER_CATEGORY = "GET_DISCOVER_CATEGORY"
export const SET_DISCOVER_CATEGORY = "SET_DISCOVER_CATEGORY"
export const DISCOVER_CATEGORY_FAILED = "DISCOVER_CATEGORY_FAILED"

export const SET_SCROLL_TO_TOP = "SET_SCROLL_TO_TOP"
export const RESET_SCROLL_TO_TOP = "RESET_SCROLL_TO_TOP"
